### ISSUE TITLE
Steam client shortcut crashes GUI after second of showing black, retries every 10 sec. Fails

### ISSUE THREAD

**Issue by ScarlettSamantha** [ValveSoftware/steam-for-linux#11668]
I installed steam via the recommended way, but everytime I click the desktop shortcut it will start for a second update if needed. But then when the GUI has to start it will show for a second flash black and disappear. 

After that it will remain in the icon bar and retries to open the GUI every 10-20 seconds before crashing the GUI again.

I am using the following versions:
```
OS: Kubuntu 24.10 clean
Kernel: Linux [REDACTED] 6.11.0-13-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Sat Nov 30 23:51:51 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Steam Version: 1733265492
Plasma: plasmashell 6.1.5
Graphics:
  Device-1: Intel Raptor Lake-S GT1 [UHD Graphics 770] driver: i915 v: kernel
  Device-2: AMD Navi 32 [Radeon RX 7700 XT / 7800 XT] driver: amdgpu
    v: kernel
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.2
    compositor: kwin_wayland driver: X: loaded: amdgpu,modesetting
    unloaded: fbdev,radeon,vesa dri: radeonsi,iris gpu: i915,amdgpu
    resolution: 1: 3440x1440 2: 3840x2160
  API: EGL v: 1.5 drivers: iris,radeonsi,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.2.3-1ubuntu1
    renderer: AMD Radeon RX 7800 XT (radeonsi navi32 LLVM 19.1.0 DRM 3.58
    6.11.0-13-generic)
  API: Vulkan v: 1.3.290 drivers: N/A surfaces: xcb,xlib,wayland
```

The weird thing is it seems to be fine if I call the `/usr/bin/steam` binary via my command line but when called via the desktop shortcut it has this behavior.

It will popup for a second then disappear tray icon will remain and then every 10-20 sec it will retry to open the GUI flashes black for a second and then close again.
```
/usr/share/themes/Breeze-Dark/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Breeze-Dark/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
Desktop state changed: desktop: { pos:    0,   0 size: 3840,3600 } primary: { pos:  191,2160 size: 3440,1440 }
Caching cursor image for left_ptr, size 32x32, serial 3, cache size = 0
BuildCompleteAppOverviewChange: 379 apps
BuildCompleteAppOverviewChange: 379 apps
steamwebhelper.sh[234924]: Using supervisor /home/scarlett/.steam/root/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-supervisor
steamwebhelper.sh[234924]: Starting steamwebhelper under bootstrap sniper steam runtime via /home/scarlett/.local/share/Steam/ubuntu12_64/steam-runtime-sniper.sh
steamwebhelper.sh[234924]: Using CEF sandbox \(try with -no-cef-sandbox if this fails\)
steamwebhelper.sh[234924]: Starting steamwebhelper with Sniper steam runtime at /home/scarlett/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/_v2-entry-point
exec ./steamwebhelper -lang=en_US -cachedir=/home/scarlett/.local/share/Steam/config/htmlcache -steampid=234462 -buildid=1733265492 -steamid=76561198025295186 -logdir=/home/scarlett/.local/share/Steam/logs -uimode=7 -startcount=1 -steamuniverse=Public -realm=Global -clientui=/home/scarlett/.local/share/Steam/clientui -steampath=/home/scarlett/.local/share/Steam/ubuntu12_32/steam -launcher=0 -no-restart-on-ui-mode-change --valve-initial-threadpool-size=10 --valve-enable-site-isolation --enable-smooth-scrolling --password-store=basic --log-file=/home/scarlett/.local/share/Steam/logs/cef_log.txt --disable-quick-menu --enable-features=PlatformHEVCDecoderSupport --disable-features=SpareRendererForSitePerProcess,DcheckIsFatal,ValveFFmpegAllowLowDelayHEVC
BuildCompleteAppOverviewChange: 379 apps
```
The shortcut that causes this points to `/usr/bin/steam` but when I manually invoke via the CLI `/usr/bin/steam` it works fine.

I have a guess that it has something to do with a locale that is being loaded in steam that is not supported and that when booted from bash that it inherits some of the env and more specifically locale.

When launching from CLI I see this message

`pressure-vessel-locale-gen: Missing locale en_NL.UTF-8 (found in $LC_MONETARY)`
Which it then will auto generate, but this message does not appear with the shortcut and therefore probably won't be able to generate it. This would also explain why the UI tries to boot but fails.

I don't know if this is related but I also get these errors when booting steam, but those might be a OS theming error but would include it just for completeness.

```
/usr/share/themes/Breeze-Dark/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", 
expected valid string constant
```

I have also included the cef_log because every since the switch it seems to have gotten way more unstable.

[cef_log.txt](https://github.com/user-attachments/files/18463450/cef_log.txt)

If you require any other information do let me know,
With kind regards,
~Scarlett
