### ISSUE TITLE
Dungeon Defenders fails to install: "invalid platform".

### ISSUE THREAD

**Issue by V10lator** [ValveSoftware/steam-for-linux#2181]
Hi,
I just tried to activate Dungeon Defenders which I purchased through the humble bundle. But it failed with the message "invalid platform":
![steam-dd](https://f.cloud.github.com/assets/1312422/268334/009374f2-8f23-11e2-8d77-f94ab80a9bcb.png)

```
Prozessor:
    Hersteller: AuthenticAMD
    Geschwindigkeit: 3300 MHz
    3 logische Prozessoren
    3 technische Prozessoren
    HyperThreading:  Nicht unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Nicht unterstützt
    SSE4a:  Unterstützt
    SSE41:  Nicht unterstützt
    SSE42:  Nicht unterstützt

Netzwerk-Informationen:
    Netzwerk-Geschwindigkeit: 

Betriebssystem:
    "Gentoo Base System release 2.1" (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 3.8.0-rc6
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11301000
    X-Fenstermanager: compiz
    Steam-Runtime-Version: <Runtime disabled>

Grafikkarte:
    Treiber: ATI Technologies Inc. AMD Radeon HD 6900 Series 

    Treiber-Version: 4.2.12172 Compatibility Profile Context 8.951
    Desktop-Farbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 60 Hz
    Keine Anbieterkenn. entdeckt
    Keine Gerätekenn. entdeckt
    Anzahl der Monitore: 1
    Keine Grafikkartenanzahl entdeckt
    Prim. Anzeigeauflösung: 1920 x 1080
    Desktop-Auflösung: 1920 x 1080
    Prim. Anzeigegröße: 47,7 cm x 26,8 cm (54,7 cm diag.)

    Kein prim. VRAM entdeckt

Soundkarte:
    Audiogerät: SigmaTel STAC9758,59

Speicher:
    RAM: 7975 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    LANG:  de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 1804086 MB
    Größter freier Festplattenspeicherblock: 1203326 MB

Installierte Software:

Neueste Fehlerberichte:
```
