### ISSUE TITLE
[L4D2] Game slowdown after some time playing

### ISSUE THREAD

**Issue by quaec** [ValveSoftware/steam-for-linux#2463]
Hi,

when playing the L4D2 Beta, after a while, the FPS are dropping significantly so that the game is unplayable. The CPU and RAM usage seems normal.

The time until this happens is varying. Sometimes right from the beginning or sometimes after a few minutes or more.

One time when the game was slow I changed the AA settings and after that the game ran fine. Other times the game crashes after changing the AA settings.

This is the first source game where I have this problem.

```
Prozessor:
    Hersteller: AuthenticAMD
    Geschwindigkeit: 3200 MHz
    4 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Nicht unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Nicht unterstützt
    SSE4a:  Unterstützt
    SSE41:  Nicht unterstützt
    SSE42:  Nicht unterstützt

Netzwerk-Informationen:
    Netzwerk-Geschwindigkeit: 

Betriebssystem:
    Ubuntu 12.04.2 LTS (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 3.5.0-18-generic
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11203000
    X-Fenstermanager: Compiz
    Steam-Runtime-Version: steam-runtime-release-i386_2013-04-16

Grafikkarte:
    Treiber: NVIDIA Corporation GeForce GTX 260/PCIe/SSE2

    Treiber-Version: 3.3.0 NVIDIA 319.17
    Desktop-Farbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 59 Hz
    Anbieterkennung: 0x10de
    Gerätekennung: 0x5e2
    Anzahl der Monitore: 2
    Anzahl der logischen Grafikkarten: 2
    Prim. Anzeigeauflösung: 1680 x 1050
    Desktop-Auflösung: 2960 x 1050
    Prim. Anzeigegröße: 47,4 cm x 29,6 cm (55,8 cm diag.)

    Primärer Bus: PCI Express 16x
    Primärer VRAM: 896 MB
    Unterstützte MSAA-Modi: 2x 4x 8x 16x 

Soundkarte:
    Audiogerät: VIA VT1708S

Speicher:
    RAM: 3953 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    LANG:  de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 928699 MB
    Größter freier Festplattenspeicherblock: 12459 MB

Installierte Software:

Neueste Fehlerberichte:
    Sun May 12 20:56:31 2013 GMT: file ''/tmp/dumps/crash_20130512225626_1.dmp'', upload yes: ''CrashID=bp-b428d4cf-f6e1-4aba-bbea-ab14a2130512''
    Sun May 12 21:13:43 2013 GMT: file ''/tmp/dumps/crash_20130512231339_1.dmp'', upload yes: ''CrashID=bp-b5f2887f-72ec-481c-95fd-e82792130512''

```
