### ISSUE TITLE
Steam Store/Community pages only load when running client from terminal

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3726]
This weird bug is happening to my desktop and my notebook which are both running Arch.
I installed NetworkManager to see if this is a problem with my network manager, but the store still only loads when i run the client from the terminal. Images of my friends load no mather what though. It seems that this is a problem with the integrated web browser the client has, am I missing a package which is needed?

I also do not know what i should debug for this. Please tell me what logs you need.

Here are my Sysinfos:

```
Prozessor:
    Hersteller: GenuineIntel
    CPU-Familie: 0x6
    CPU-Modell: 0x2a
    CPU-Stepping: 0x7
    CPU-Typ: 0x0
    Geschwindigkeit: 5900 MHz
    4 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Nicht unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Nicht unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt

Netzwerkinformationen:
    Netzwerk-Geschwindigkeit: 

Betriebssystem:
    "Arch Linux" (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 3.18.6-1-ARCH
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11701000
    X-Fenstermanager: i3
    Steam-Runtime-Version: steam-runtime-release_2015-01-06

Grafikkarte:
    Treiber: X.Org Gallium 0.4 on AMD HAWAII

    Treiberversion: 3.0 Mesa 10.4.4
    OpenGL-Version: 3.0
    Desktop-Farbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 60 Hz
    Anbieterkennung: 0x1002
    Gerätekennung: 0x67b1
    Anzahl der Monitore: 1
    Anzahl der logischen Grafikkarten: 1
    Prim. Anzeigeauflösung: 1920 x 1080
    Desktopauflösung: 1920 x 1080
    Prim. Anzeigegröße: 53,1 cm x 29,9 cm (60,9 cm diag.)

    Kein prim. VRAM entdeckt

Soundkarte:
    Audiogerät: AV200

Speicher:
    RAM: 7886 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    SPRACHE: de_DE.utf8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 184795 MB
    Größter freier Festplattenspeicherblock: 126373 MB

Installierte Software:

Neueste Fehlerberichte:
```
