### ISSUE TITLE
Unable to start big picture since few weeks

### ISSUE THREAD

**Issue by czarnyckm** [ValveSoftware/steam-for-linux#4472]
#### Your system information

* Steam client version: few last updates currently  May 31 2016 23:03:59 API v017 
* Distribution (e.g. Ubuntu): Debian sid  64bit alsa
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

I do get a SIGSEGV, Segmentation fault every time when i going to start the steam in big picture

#### Steps for reproducing this issue:

1. Start big picture on system with multiple sound cards (without pulse audio)

gdb
```
[New Thread 0xe3781b40 (LWP 7798)]
[New Thread 0xe5bffb40 (LWP 7799)]
[New Thread 0xe032eb40 (LWP 7800)]
[New Thread 0xdfb2db40 (LWP 7801)]
[New Thread 0xdf32cb40 (LWP 7802)]
[New Thread 0xddfe6b40 (LWP 7803)]
[New Thread 0xdd4eeb40 (LWP 7804)]

Program received signal SIGSEGV, Segmentation fault.
0xf72a3701 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
(gdb) bt
#0  0xf72a3701 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#1  0xf72a33db in strdup () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#2  0xf0f404fe in ?? () from /home/arta/.steam/ubuntu12_32/libSDL2-2.0.so.0
#3  0xf0f81f89 in ?? () from /home/arta/.steam/ubuntu12_32/libSDL2-2.0.so.0
#4  0xf0f82140 in ?? () from /home/arta/.steam/ubuntu12_32/libSDL2-2.0.so.0
#5  0xf0ede3af in ?? () from /home/arta/.steam/ubuntu12_32/libSDL2-2.0.so.0
#6  0xf0edba75 in ?? () from /home/arta/.steam/ubuntu12_32/libSDL2-2.0.so.0
#7  0xf0f0b503 in SDL_Init () from /home/arta/.steam/ubuntu12_32/libSDL2-2.0.so.0
#8  0xe05a1fb5 in ?? () from /home/arta/.steam/ubuntu12_32/panorama/panorama.so
#9  0xf2492308 in ?? () from /home/arta/.steam/ubuntu12_32/steamui.so
#10 0xf2525e8a in ?? () from /home/arta/.steam/ubuntu12_32/steamui.so
#11 0xf251e3cb in ?? () from /home/arta/.steam/ubuntu12_32/steamui.so
#12 0xf2520ba5 in ?? () from /home/arta/.steam/ubuntu12_32/steamui.so
#13 0xf297db64 in ?? () from /home/arta/.steam/ubuntu12_32/steamui.so
#14 0xef822814 in ?? () from /home/arta/.steam/ubuntu12_32/vgui2_s.so
#15 0xef819ae6 in ?? () from /home/arta/.steam/ubuntu12_32/vgui2_s.so
#16 0xef81b5cf in ?? () from /home/arta/.steam/ubuntu12_32/vgui2_s.so
#17 0xef81ba30 in ?? () from /home/arta/.steam/ubuntu12_32/vgui2_s.so
#18 0xf2491013 in ?? () from /home/arta/.steam/ubuntu12_32/steamui.so
#19 0xf249350b in ?? () from /home/arta/.steam/ubuntu12_32/steamui.so
#20 0xf2494b45 in ?? () from /home/arta/.steam/ubuntu12_32/steamui.so
#21 0x56630d4a in RunSteam(int, char**, bool) ()
#22 0x566198f2 in ?? ()
#23 0xf7247637 in __libc_start_main () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
#24 0x5661c009 in _start ()
```

System Info:

```
Computerinformationen:
    Hersteller: Unknown
    Modell: Unknown
    Formfaktor: Desktop
    Keine Touch-Eingabe erkannt
    
Prozessor:
    CPU-Hersteller: AuthenticAMD
    CPU-Familie: 0x15
    CPU-Modell: 0x2
    CPU-Stepping: 0x0
    CPU-Typ: 0x0
    Geschwindigkeit: 4000 MHz
    8 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt
    AES: Unterstützt
    AVX: Unterstützt
    CMPXCHG16B: Unterstützt
    LAHF/SAHF: Unterstützt
    PrefetchW: Nicht unterstützt
    
Netzwerkinformationen:
    Netzwerk-Geschwindigkeit: 
    
Betriebssystem:
    Debian GNU/Linux unstable (sid) (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 4.6.0
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11803000
    X-Fenstermanager: KWin
    Steam-Runtime-Version: steam-runtime-release_2016-02-23
    
Grafikkarte:
    Treiber: NVIDIA Corporation GeForce GTX 960/PCIe/SSE2

    Treiberversion: 4.5.0 NVIDIA 367.18
    OpenGL-Version: 4.5
    Desktop-Farbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 59 Hz
    Anbieterkennung: 0x10de
    Gerätekennung: 0x1401
    Revision nicht gefunden
    Anzahl der Monitore: 1
    Anzahl der logischen Grafikkarten: 1
    Prim. Anzeigeauflösung: 2560 x 1440
    Desktopauflösung: 2560 x 1440
    Prim. Anzeigegröße: 52,7 cm x 29,6 cm (60,4 cm diag.)

    Primärer Bus: PCI Express 16x
    Primärer VRAM: 4096 MB
    Unterstützte MSAA-Modi: 2x 4x 8x 16x 
    
Soundkarte:
    Audiogerät: 20K2
    
Speicher:
    RAM: 32128 MB
    
Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    SPRACHE: de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 614100 MB
    Größter freier Festplattenspeicherblock: 200595 MB
    VR-Headset: Keines gefunden
    
    Wed Jun  1 16:04:27 2016 GMT: file ''/tmp/dumps/assert_20160601180300_1.dmp'', upload yes: ''CrashID=bp-d2115e42-dc06-48f2-a310-521122160601''
    Wed Jun  1 16:27:19 2016 GMT: file ''/tmp/dumps/assert_20160601180440_1.dmp'', upload yes: ''CrashID=bp-344f02a6-b18b-40c5-ba8a-61ef02160601''
    Wed Jun  1 16:43:15 2016 GMT: file ''/tmp/dumps/assert_20160601183024_1.dmp'', upload yes: ''CrashID=bp-afe63236-41a5-4bc1-8e13-334962160601''
    
```

thanks
Piotr
