### ISSUE TITLE
Steam freezes (Linux - Ubuntu)

### ISSUE THREAD

**Issue by LolmanCZ** [ValveSoftware/steam-for-linux#5322]
#### Your system information

* Steam client version (build number or date): latest (1513371133)?
* Distribution (e.g. Ubuntu): Ubuntu 64bit 16.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

Graphics Card : Nvidia GeForce GTX 750 Ti
Driver Version: 375.66

#### Please describe your issue in as much detail as possible:
Steam starts normally (The sign in screen shows up) but then everything starts to freeze for 5 sec. every 10 sec. and it continues even after I stop Steam. Sometimes it even "crashes" and logs me off my pc user.

Here is log when I run Steam from the console(LXTerminal):
https://gist.github.com/LolmanCZ/de6b4685e2a1bd50a076223e56e6cec5
(I am new here and I don't know if I linked it right, please don't hate me)

#### Steps for reproducing this issue:

1. Start Steam
2. Wait

**Comment by kisak-valve** [comment]
Hello @LolmanCZ, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

The symptoms you've described suggest there's a general system issue going on here. There's a chance dmesg is catching a hint to help troubleshoot after the quirk behavior starts.

**Comment by LolmanCZ** [comment]
Hi @kisak-valve, I'm sorry but I can't give you my system information from Steam because I can't log in with my Steam account because I'm stuck on the Steam log in screen and I can't type in my password because it freezes and then when I finally enter the password(between the freezes) it crashes and logs me off my pc user.

**Comment by LolmanCZ** [comment]
Hi @kisak-valve, I'm sorry but I can't give you my system information from Steam because I can't log in with my Steam account because I'm stuck on the Steam log in screen and I can't type in my password because it freezes and then when I finally enter the password(between the freezes) it crashes and logs me off my pc user.

**Comment by kisak-valve** [comment]
That's okay, the particular details I was curious about was what kernel version is being used, the cpu model, and confirmation that the 32 bit opengl driver was what you expected it to be.

There's been some recent chatter outside of Github that Intel's Meltdown workaround could cause this kind of symptom on AMD cpus and booting with the `nopti` kernel option would workaround the workaround, but there's not much info to suggest that's what's going on here.

**Comment by LolmanCZ** [comment]
It has gone worse. Now it "crashes" and logs me off my pc user every time after the second freeze and it crashes immediately after I log back in so I now have to restart my pc. I tried to get a dmesg log but I wasn't fast enough.

**Comment by LolmanCZ** [comment]
One more information I forgot : it started happening since the last Steam update (I don't know when exactly it was). Before that update it was fine.

**Comment by toddmb** [comment]
I have the same problem here. Since the more recent Steam update on Linux. After games update or install, Steam freezes. The same for uninstalling games on Steam for Linux.
I'm running Ubuntu MATE 16.04.3. 

Graphics Card: GTX 970
NVIDIA Driver 387.34

**Comment by joder666** [comment]
I get this or something similar, my system just freezes a couple of seconds after running Steam. It does no even manages to open i just freezes the whole system after 2 or 4 seconds after.

Pretty sure this is happening due the the f@ck up about meltdown and specter thingy, the patches to "solved" (can't be solved that's the reality) are messing something really bad.

I am using opensuse Tumbleweed, AMD processor FX 8320 with kernel version 4.14.12 (this one ships with patches for the fuck up) and nvidia driver 384.111. All was good and dandy  when i was running kernel 4.12.8.

**Comment by LolmanCZ** [comment]
I don't know what happened but this time I started Steam it didn't freeze so I got the info:
https://gist.github.com/LolmanCZ/71e88f2efc83d44f36de4e0390165296
It is weird because it froze the next time I started it so I don't know what caused it to not freeze.

**Comment by joder666** [comment]
All its working fine for me with the latest updates opensuse tumblweed, although i do boot with the meltdown and specter stuff disable.

**Comment by LolmanCZ** [comment]
Does anyone know what exactly changed in Steam and caused this problem? Is there any chance it will be fixed in the next update? Or do I have to try to fix it my self.

**Comment by V10lator** [comment]
@LolmanCZ Is this fixed for you or why did you close it? Just asking as for me the bug seems to be still there. The `nopti` boot parameter is not an option here for security reasons (KPTI is more than just a fix for Meltdown) and Steam causing such massive context switches that the whole OS hangs seems to be a bug of Steam.

**Comment by kisak-valve** [comment]
Hello @V10lator, the rough edges of KPTI has been taken care of since the discussion on this issue report. Unless your system that was last updated within weeks of the discussion, then that testing suggestion is no longer relevant to your system.

**Comment by V10lator** [comment]
Hi @kisak-valve, I'm using kernel 4.17.3 with `CONFIG_PAGE_TABLE_ISOLATION=y` and I am experiencing this slowdown (when I close Steam the whole system hangs for around 30 seconds). If I boot with `nopti` everything seems fine but again: This is not a option here.

````
Computerinformationen:
    Hersteller: Unknown
    Modell: Unknown
    Formfaktor: Desktop
    Keine Touch-Eingabe erkannt

Prozessor:
    CPU-Hersteller: AuthenticAMD
    CPU-Marke: AMD FX(tm)-8350 Eight-Core Processor           
    CPU-Familie: 0x15
    CPU-Modell: 0x2
    CPU-Stepping: 0x0
    CPU-Typ: 0x0
    Geschwindigkeit: 4400 MHz
    8 logische Prozessoren
    8 technische Prozessoren
    HyperThreading:  Nicht unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt
    AES: Unterstützt
    AVX: Unterstützt
    CMPXCHG16B: Unterstützt
    LAHF/SAHF: Unterstützt
    PrefetchW: Nicht unterstützt

Betriebssystem:
    "NAME=Gentoo" (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 4.17.3
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11905000
    X-Fenstermanager: Openbox
    Steam-Runtime-Version: steam-runtime-beta-release_2017-10-05

Grafikkarte:
    Treiber: X.Org Radeon RX 580 Series (POLARIS10, DRM 3.25.0, 4.17.3, LLVM 5.0.2)
    Treiberversion: 3.1 Mesa 18.1.3
    OpenGL-Version: 3.1
    Desktopfarbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 60 Hz
    Keine Anbieterkenn. entdeckt
    Keine Gerätekenn. entdeckt
    Revision nicht gefunden
    Anzahl der Monitore: 2
    Keine Grafikkartenanzahl entdeckt
    Prim. Anzeigeauflösung: 1920 x 1080
    Desktopauflösung: 1920 x 1080
    Prim. Anzeigegröße: 34,84" x 19,61" (39,96" diag)
 88,5cm x 49,8cm (101,5cm diag)
    Primärer VRAM: 8192 MB

Soundkarte:
    Audiogerät: Realtek Generic

Speicher:
    RAM: 15973 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    SPRACHE: de_DE.UTF-8
    Verfügbarer Festplattenspeicher insgesamt: 1669027 MB
    Größter freier Festplattenspeicherblock: 148968 MB
    VR-Headset: Keines gefunden

Neueste Fehlerberichte:

````
