### ISSUE TITLE
DLC tab is always empty

### ISSUE THREAD

**Issue by fkrauthan** [ValveSoftware/steam-for-linux#60]
If i click on a windows game right click Settings and then go to the DLC view it always say that i don't have any DLCs. But I am sure that for example for Magicka I bought DLCs and also after activating my "Dungeon Defenders + All DLC" from humble bundle the DLC tab for Dungeon Defenders says no DLCs. 

```
Prozessor:
    Hersteller: GenuineIntel
    Geschwindigkeit: 2501 MHz
    4 logische Prozessoren
    2 technische Prozessoren
    HyperThreading:  Unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Nicht unterstützt
    SSE41:  Unterstützt
    SSE42:  Unterstützt

Netzwerk-Informationen:
    Netzwerk-Geschwindigkeit:  

Betriebssystem:
    "Arch Linux" (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 3.6.10-1-ARCH
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11301000

Grafikkarte:
    Treiber: Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2

    Treiber-Version: 3.0 Mesa 9.0.1
    Desktop-Farbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 60 Hz
    Anbieterkennung: 0x8086
    Gerätekennung: 0x126
    Anzahl der Monitore: 1
    Anzahl der logischen Grafikkarten: 1
    Prim. Anzeigeauflösung: 1920 x 1080
    Desktop-Auflösung: 1920 x 1080
    Prim. Anzeigegröße: 34,4 cm x 19,3 cm (39,4 cm diag.)

    Kein prim. VRAM entdeckt

Soundkarte:
    Audiogerät: Intel CougarPoint HDMI

Speicher:
    RAM: 3841 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    LANG:  de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 209760 MB
    Größter freier Festplattenspeicherblock: 36335 MB
```
