### ISSUE TITLE
Streaming games just ends up with black screen ( Optimus/Prime system)

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#8106]
#### Your system information

* Steam client version (build number or date): Sep 23 2021
* Distribution (e.g. Ubuntu): Linux Mint 20.2
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

As said in the title on such setup that is launched with ```__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only``` streaming ANY game (Proton and native,both GL and Vulkan) to SteamLink Android app ( will likely have same result on any other versions) ends up with getting just a black screen on receiving device while audio and input works. So likely encoding on host device fails with such setups.

- Output of Steam client sys info gathering tool:

https://gist.github.com/Leopard1907/8ee0d7fc9174d1f7e818aa86dd654cea

- System info (inxi -SMGxx):

https://gist.github.com/Leopard1907/e0983505aa30b6798ee8e40fc031b324

#### Steps for reproducing this issue:

1. Get hands on an Optimus/Prime laptop and use vars above
2. Install SteamLink to any device to use it as a receiver device
3. Try streaming ANY game

**Comment by xPathin** [comment]
One thing to add, in my case only BPM causes this Black Screen, however as soon as I start a game, the video is streaming fine.  
Running sway (wayland) on Arch.

**Comment by Leopard1907** [comment]
One year passed since this report was created, still same issue. 

System info gathered from Steam client:

https://gist.github.com/Leopard1907/c0d0491416e5a83ed5119953da664f12

`inxi -SMGxx` output:

```
System:
  Host: asus-fx553vd Kernel: 5.19.13-arch1-1 arch: x86_64 bits: 64
    compiler: gcc v: 12.2.0 Desktop: KDE Plasma v: 5.25.5 tk: Qt v: 5.15.6
    wm: kwin_x11 dm: SDDM Distro: EndeavourOS base: Arch Linux
Machine:
  Type: Laptop System: ASUSTeK product: GL553VD v: 1.0
    serial: <superuser required>
  Mobo: ASUSTeK model: GL553VD v: 1.0 serial: <superuser required>
    UEFI: American Megatrends v: GL553VD.308 date: 04/29/2019
Graphics:
  Device-1: Intel HD Graphics 630 vendor: ASUSTeK driver: i915 v: kernel
    arch: Gen-9.5 ports: active: eDP-1 empty: HDMI-A-1 bus-ID: 00:02.0
    chip-ID: 8086:591b
  Device-2: NVIDIA GP107M [GeForce GTX 1050 Mobile] vendor: ASUSTeK
    driver: nvidia v: 520.56.06 arch: Pascal pcie: speed: 2.5 GT/s lanes: 16
    bus-ID: 01:00.0 chip-ID: 10de:1c8d
  Device-3: Realtek USB2.0 HD UVC WebCam type: USB driver: uvcvideo
    bus-ID: 1-6:3 chip-ID: 0bda:57f5
  Display: x11 server: X.Org v: 21.1.4 compositor: kwin_x11 driver: X:
    loaded: intel,nvidia unloaded: fbdev,modesetting,vesa alternate: nouveau,nv
    dri: i965 gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: eDP-1 mapped: eDP1 model: BOE Display 0x069c res: 1920x1080
    dpi: 143 diag: 394mm (15.5")
  OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 22.1.7
    direct render: Yes
```
