### ISSUE TITLE
steam remote play - ctd and restart of steam on host when trying to stream

### ISSUE THREAD

**Issue by TheTee82** [ValveSoftware/steam-for-linux#8541]
#### Your system information

* Steam client version (build number or date): `1650062193` - ` Apr 15 2022, at 20:35:56`
* Distribution (e.g. Ubuntu): `Arch` - `manjarolinux 21.2.6 64-bit`
* Opted into Steam client beta?: **Yes**
* Have you checked for system updates?: **Yes**

Detailed information:
**Remote Play Host:**

```
System:
  Host: linuxbox Kernel: 5.17.1-3-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.4 Distro: Manjaro Linux
Graphics:
  Device-1: AMD Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] driver: amdgpu
    v: kernel
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: amdgpu
    unloaded: modesetting,radeon gpu: amdgpu resolution: 2560x1440
  OpenGL: renderer: AMD Radeon RX 6900 XT (SIENNA_CICHLID DRM 3.44.0
    5.17.1-3-MANJARO LLVM 13.0.1)
    v: 4.6 Mesa 21.3.8
  ```
  
**Remote Play Client:**
* Distribution and steam version exactly the same as host-system

```
System:
  Host: remoteclient Kernel: 5.17.1-3-MANJARO arch: x86_64 bits: 64 Console: pty pts/1
    Distro: Manjaro Linux
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1080] driver: nvidia v: 510.60.02
  Display: x11 server: X.org v: 1.21.1.3 driver: X: loaded: nvidia gpu: nvidia tty: 150x76
  Message: GL data unavailable in console. Try -G --display
```
 
 --- 

#### Please describe your issue in as much detail as possible:
After latest update to kernel `5.17` and mesa `21.3.8`:
- when trying to launch a game via `Stream` (remote play) from a different client
- Steam switches to BPM (as expected) on host-machine (this machine)
- Steam tries launching a game (eg. `Control - App ID: 870780` which worked fine just the other day)
- Steam crashes to desktop and restarts automatically on host-machine

For more detail see: https://gist.github.com/TheTee82/bd2a9c19e2dd392c736e7b7ffba86c1f
( I believe https://gist.github.com/TheTee82/bd2a9c19e2dd392c736e7b7ffba86c1f#file-gistfile1-txt-L285-L306 might be the most relevant part here ) 

- CrashID=`bp-14db574c-2b82-448a-9791-176122220417`

---

#### Steps for reproducing this issue:

1. Update Manjaro to latest mesa and kernel (Host)
2. launch steam on host and client
2a. you can also try launching Steam Link (provided via flatpak - `com.valvesoftware.SteamLink` -  `1.1.89.225` - `stable`) which results in the issue when trying to "Start Streaming" / connecting to host
3. try to "Stream" game from host to client
3a. this happens with various different games - so I can't rule out a Proton issue but when running on host machine directly is working fine
